services:
  fastapi_app:
    container_name: fastapi_app
    build:
      context: .
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:8
    depends_on:
      - postgres
    env_file:
      - ".env"
    ports:
      - "5050:80"

  migrations:
    container_name: migrations
    build:
      context: .
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ".env"
    volumes:
      - ./src:/app

volumes:
  postgres_data: